wordslist = ("python", "program", "developer", "variable", "function", "loop", "condition", "syntax", "compile", "execute",
         "keyboard", "monitor", "internet", "server", "client", "socket", "memory", "binary", "decimal", "integer",
         "float", "string", "boolean", "array", "list", "tuple", "dictionary", "set", "exception", "import",
         "module", "object", "class", "method", "inheritance", "encapsulation", "polymorphism", "debug", "algorithm",
         "data",
         "stack", "queue", "tree", "graph", "search", "sort", "recursion", "file", "input", "output", "apple", "banana",
         "orange", "grapes", "melon", "peach", "cherry", "lemon", "avocado", "papaya",
         "carrot", "potato", "tomato", "onion", "garlic", "cabbage", "spinach", "broccoli", "pepper", "celery",
         "coffee", "tea", "water", "juice", "soda", "milk", "bread", "cheese", "butter", "yogurt",
         "pencil", "eraser", "notebook", "marker", "ruler", "scissors", "glue", "paper", "folder", "stapler",
         "rabbit", "tiger", "lion", "giraffe", "elephant", "zebra", "monkey", "bear", "wolf", "kangaroo",
         "ocean", "river", "mountain", "valley", "forest", "desert", "island", "volcano", "glacier", "cave",
         "train", "plane", "bicycle", "car", "bus", "subway", "scooter", "skateboard", "tram", "boat",
         "castle", "village", "market", "church", "bridge", "tower", "tunnel", "airport", "stadium", "palace",
         "winter", "spring", "summer", "autumn", "thunder", "lightning", "rainbow", "hurricane", "blizzard", "fog",
         "friend", "enemy", "family", "teacher", "student", "doctor", "artist", "singer", "dancer", "farmer", "rocket",
         "planet", "galaxy", "comet", "meteor", "spaceship", "astronaut", "telescope", "satellite", "universe",
         "energy", "gravity", "atom", "molecule", "element", "crystal", "oxygen", "hydrogen", "carbon", "helium",
         "guitar", "violin", "trumpet", "piano", "drums", "flute", "singer", "choir", "music", "melody",
         "circus", "clown", "juggler", "acrobat", "magician", "tent", "ticket", "audience", "stage", "performer",
         "pirate", "sword", "treasure", "island", "parrot", "compass", "ship", "anchor", "crew", "captain",
         "dragon", "wizard", "castle", "sword", "magic", "potion", "knight", "shield", "quest", "kingdom",
         "soccer", "tennis", "cricket", "baseball", "hockey", "boxing", "skiing", "cycling", "swimming", "running",
         "puzzle", "riddle", "number", "letter", "symbol", "pattern", "cipher", "code", "message", "clue",
         "window", "curtain", "pillow", "blanket", "lamp", "sofa", "closet", "mirror", "carpet", "ceiling",
         "animal", "insect", "reptile", "mammal", "amphibian", "bird", "fish", "whale", "shark", "octopus")
